# Generated by Django 6.0.1 on 2026-01-09 10:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivareity',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
