# Generated by Django 6.0.1 on 2026-01-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_alter_chaivareity_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivareity',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
