# Generated by Django 6.0.1 on 2026-01-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0004_chaicertificate_chaireview_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='chai_variety',
            new_name='chai_varieties',
        ),
    ]
